apiVersion: v1
kind: ConfigMap
metadata:
  name: prompts
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "inference.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.prompts }}
  {{ $key }}.txt: |
    {{- $value | nindent 4 }}
  {{- end }}
