namespace: lang-learn

frontend:
  image:
    repository: ghcr.io/rickdevma100/frontend
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

ingress:
  enabled: true
  ingressClassName: public
  host: langlearn.local

apiUrl: "http://lang-learn-inference-predictor.lang-learn.svc.cluster.local"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
